### ISSUE TITLE
ADB global installation not found.

### ISSUE THREAD

**Issue by JCStrainer** [whitewhidow/quest-sidenoder#10]
Hello,

I installed all dependencies and adb is working from the command line, but I still get this error message when I open the program.

**Comment by whitewhidow** [comment]
but is it working GLOBALLY from the command line ? (eg added to $PATH)
how did you "install" adb ?

(the adb check is not really error prone)

**Comment by JCStrainer** [comment]
I added the platform tools folder to path as described.

Yes, it is working globally in cmd.

**Comment by whitewhidow** [comment]
ive just added a windows installer bat script,    that *should* take care of adb, aapt and rclone for you.
https://whitewhidow.github.io/quest-sidenoder/

**Comment by whitewhidow** [comment]
@JCStrainer please verify if the bat file fixes the issue for you. thx

**Comment by Waz999** [comment]
I get this error too. I have run the bat file but it encounters issues. When unzipping rclone, adb and aapt it says The system cannot find the path specified.

**Comment by whitewhidow** [comment]
@Waz999 could you please paste the command and output pls
thx

**Comment by whitewhidow** [comment]
@walterwg1 , same as @Waz999 ,  please show a screen of what you are actually doing..

>  When unzipping rclone, adb and aapt it says The system cannot find the path specified.

Is not a description that help...   please show what is happening,   it cant find 7zip ?

**Comment by walterwg1** [comment]
I found the problem the the environment variable was getting overwritten. There was two "SideNoder-win32-x64\SideNoder-win32-x64\sideloader_deps\android-9" change one to show "SideNoder-win32-x64\SideNoder-win32-x64\sideloader_deps\platform-tools"

**Comment by whitewhidow** [comment]
> I found the problem the the environment variable was getting overwritten. There was two "SideNoder-win32-x64\SideNoder-win32-x64\sideloader_deps\android-9" change one to show "SideNoder-win32-x64\SideNoder-win32-x64\sideloader_deps\platform-tools"

so you had a diff issue then the other person ? 

Can you delete both dircetories form PATH, rerun the installer,   and verify that it is actually creating 2 duplicate entries in PATH ? 

seems very odd since the code does: 
```
:: TODO:check if already in path
setx PATH "%userpath%;%~dp0sideloader_deps\platform-tools"
setx PATH "%userpath%;%~dp0sideloader_deps\android-9"
```

**Comment by EveningPerson** [comment]
There is no ADB file for me?

**Comment by EveningPerson** [comment]
Heb je toevallig discord ofzo?
Want echt vervelnd

**Comment by EveningPerson** [comment]
Well I do have it, but it says i Dont

**Comment by whitewhidow** [comment]
> There is no ADB file for me?
please 1 dont hijack this ticket, please 2 post in english, and please 3 edit your post instead of posting three oneline messages.

**Comment by Waz999** [comment]
> @Waz999 could you please paste the command and output pls
> thx

Which command? Also here's a screenshot: https://imgur.com/a/3DXrrvk

**Comment by whitewhidow** [comment]
> > @Waz999 could you please paste the command and output pls
> > thx
> 
> Which command? Also here's a screenshot: https://imgur.com/a/3DXrrvk

this would mean that the following have failed for some reason :
```
"C:\Program Files\7-Zip\7z.exe" x -y rclone.zip > NUL
"C:\Program Files\7-Zip\7z.exe" x -y android-tools.zip > NUL
"C:\Program Files\7-Zip\7z.exe" x -y aapt.zip > NUL
```
In beginning of your screenshot i see it indicates that the script thinks 7zip is not installed, and normally proceeds to download the installer, and should start the 7zip install, before continuing the rest of the process.

can you confirm, Did it infact start the 7zip installer and finish it correctly ?
can you confirm, Does the 7zip installer maybe propopse a different path for you ?

Overall, Can you check wether or not 7zip is installed, and where?

Thx

**Comment by Waz999** [comment]
> > > @Waz999 could you please paste the command and output pls
> > > thx
> > 
> > 
> > Which command? Also here's a screenshot: https://imgur.com/a/3DXrrvk
> 
> this would mean that the following have failed for some reason :
> 
> ```
> "C:\Program Files\7-Zip\7z.exe" x -y rclone.zip > NUL
> "C:\Program Files\7-Zip\7z.exe" x -y android-tools.zip > NUL
> "C:\Program Files\7-Zip\7z.exe" x -y aapt.zip > NUL
> ```
> 
> In beginning of your screenshot i see it indicates that the windows-install script thinks 7zip is not yet installed, and normally proceeds to download the installer, and should start the 7zip install, before continuing the rest of the process.
> 
> can you confirm, Did it infact start the 7zip installer and finish it correctly ?
> can you confirm, Does the 7zip installer maybe propopse a different path for you ?
> 
> Overall, Can you check wether or not 7zip is installed, and where?
> 
> Thx

Yep, that's what's failed. I do have 7zip installed. But it's on a different local drive. I'll relocate to C drive and test from there. Thanks!

**Comment by whitewhidow** [comment]
you mean the error saying "cannot find the path specified" ?  or does the installer now run without issue but the app is still throwing an error ?
(did you maybe accidentally copy it to `C:\Program Files (x86)\7-Zip\` instead of `C:\Program Files\7-Zip\`)
(ps: will also update installer tmrw only use relative paths, to avoid this drive letter issue altogether )

**Comment by Waz999** [comment]
> you mean the error saying "cannot find the path specified" ? or does the installer now run without issue but the app is still throwing an error ?
> (did you maybe accidentally copy it to `C:\Program Files (x86)\7-Zip\` instead of `C:\Program Files\7-Zip\`)
> (ps: will also update installer tmrw only use relative paths, to avoid this drive letter issue altogether )

New screenshopt: https://imgur.com/a/fy6Zr8z

**Comment by whitewhidow** [comment]
Can you check the PATH windows variable, i assume it is the same issue as walter has had above, and the installer did not add the platform-tools folder to the PATH var correctly ?

how to check PATH via the windows gui:
(https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

Could you verify that the platform-tools directory is indeed missing ?    and if it IS indeed missing, could you try downloading and running the following updated windows-installer from : `https://github.com/whitewhidow/quest-sidenoder/blob/main/windows-install.bat`
And verifying wether the fix i added to it a few hours ago, now actually adds the second directory to PATH (if it still does not, you can just add it manually for now, like walter did, so that you can atleast continue, and then i will attempt to verify the new windows bat script myself later)

**Comment by Waz999** [comment]
YESSS! That new bat file did it. You're awesome. Thank you for the assistance! ;)

**Comment by whitewhidow** [comment]
You're welcome,   i hope this fixes the issue for @JCStrainer aswell.
@JCStrainer I will close this ticket for now, feel free to reopen it or open a new one if needed.

thx

**Comment by walterwg1** [comment]
Sorry I am just now seeing this. I didn't get a chance to reinstall but glad the issue was corrected. Love the program thanks for your hard work.
