### ISSUE TITLE
how to fix wrong repo

### ISSUE THREAD

**Issue by hazriex** [whitewhidow/quest-sidenoder#106]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/OSX/LINUX]
 - Running via binary or npm start
 - Version [e.g. v0.0.3-alpa]

**Additional context**

**Comment by whitewhidow** [comment]
READ README, WRONG REPO
