### ISSUE TITLE
Add Progress Indicators for Download & Install

### ISSUE THREAD

**Issue by evilryan** [whitewhidow/quest-sidenoder#23]
Currently the application does not provide any information  about:

Size of the item to be downloaded/installed.
Progress of the download.
Speed of the download.
Progress of the installation/copy steps.

These would be nice to have.

**Comment by ov3rk1ll** [comment]
Just as a general note:

when starting rclone mount with the `--rc` flag (and `--rc-no-auth` for ease of use) it is possible to get transfer data by doing a HTTP-POST to `http://127.0.0.1:5572/core/stats`.  See https://rclone.org/rc/#core-stats for the format of the response.

Easiest solution would to be to check this URL every X seconds and show a global process indicator. E.g. next to the device and mount status boxed in the top right.

**Comment by whitewhidow** [comment]
closing as added to v0.0.6-alpha (indicator for network activity during sideloading)
