### ISSUE TITLE
Add an option to keep the downloaded content.

### ISSUE THREAD

**Issue by evilryan** [whitewhidow/quest-sidenoder#24]
It would be nice to have the option to keep a copy of the downloaded content for future re-use if needed, to save time.

**Comment by whitewhidow** [comment]
You can access the files at any time, straight from the mounted folder (using explorer, finder, nautilus, etc) and jsut copy any folder to your local disk for future re-use (see the "mount folder" location on the main page in the app)

**Comment by evilryan** [comment]
Okay, understood. Thanks!
