### ISSUE TITLE
Change to not require re-checking for updates after each update.

### ISSUE THREAD

**Issue by evilryan** [whitewhidow/quest-sidenoder#25]
Currently, after each update, it returns you to the "Installed APP's" screen, requiring to re-click "Click to check mount for updates [BETA]" after every single update. This is a poor experience when you have several updates.

**Comment by whitewhidow** [comment]
not forgotten,   will start taking care of this one as i take care of the settings page

**Comment by whitewhidow** [comment]
@evilryan  can you pls check if this is still an issue in v0.0.10
https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.10

thx

**Comment by evilryan** [comment]
> @evilryan can you pls check if this is still an issue in v0.0.10
> https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.10
> 
> thx

Sorry, I grabbed v0.0.11 and confirm that this enhancement request is in place and working in that it I can now click "Update" to the remaining apps in view.  This is great, thank you for this, so we can consider this enhancement request closed.

However, the apps that are updated, and the "Update to xxxxx" button gets removed, however to the right of their VersionCode: line, it has the rotating arrows and a "Please wait" message, which never goes away. The arrows just continue to rotate.

**Comment by whitewhidow** [comment]
fixed in 
https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.12
Please confirm.
Once confirmed will be promoted from pre-release to stable.
