### ISSUE TITLE
Rewrite UI using a framework

### ISSUE THREAD

**Issue by ov3rk1ll** [whitewhidow/quest-sidenoder#30]
The current frontend code is split up across different templates which will eventually make this very hard to maintain in the long run.

Have you considered using some kind of frontend framework to better organize the code? Something like Vue, React, Angular, etc.  
They all should work with `ipcRenderer` so the general backend architecture can be kept as it is.

**Comment by whitewhidow** [comment]
ofc but im not actually a js or frontend guy, so ALSO taking the time to use a proper frontend framework, would make things progress much slower for me unfortunately, the split across home, browse and installed is not good, i know,   ut at this point i dont know how to quickly, and easily split it up, without having to spend much time on it, aquiring new knowledge, i'd rather put the time into features now,   and rewrite the FE later

**Comment by ov3rk1ll** [comment]
I was looking for something to look into learning Vue.js so I have created a version of this app at https://github.com/ov3rk1ll/vue-sidenoder that uses Vue as a frontend-library.

I reused most of the backend code but there are some core differences:

- main.js was moved to src/electron/background.js
- functions.js was split into different files in src/electron/
- Code is generally imported using JavaScript modules. Babel is used to transpile both front and backend code
- All `adb` calls are implemented using a modified `adbkit` library so there is no hard dependency on an adb executable
- Rclone is used in remote control mode instead of mount so all listing and downloading is done through the remote (http) API instead of the filesystem
- Twig templates are now using Vue. Any frontend JS is contained in the .vue file of the component

Feel free to check out the [project](https://github.com/ov3rk1ll/vue-sidenoder) if you want. I have only tested on Windows so far but I don't see any reasons why this shouldn't run on other platforms.

This port/rewrite was more of a learning tool for me to do not feel obligated to bring any of the changes back into this project if that is not something you want to look at.

**Comment by colthreepv** [comment]
it looks like a good work @ov3rk1ll, many things have been implemented, not only an FE rewrite

Also I think 4 eyes are always better than 2 for any kind of project, hope something will come out of this

**Comment by whitewhidow** [comment]
You might want to put this into (several) PR's so that i can see actual changes

A few comments (havent actually run locally, just looked briefly at the comment here and the packagejson in the repo)
- Rclone was intentionally using the mount approach, so that it all works the same as it does for regular pre-downloaded local content, will the other approach not break this ?
- adbkit still needs the actual adb executable from what i can tell ?
-  i suggest we split these changes up into functional changes, and (frontend)framework changes. as this will make it easier for me ?

**Comment by ov3rk1ll** [comment]
> You might want to put this into (several) PR's so that i can see actual changes

I'll look into this but must of the backend code is only somewhat compatible with the the current int his repo since a many of the IPC was also changed to some extent in either name or arguments/return values.

> * Rclone was intentionally using the mount approach, so that it all works the same as it does for regular pre-downloaded local content, will the other approach not break this ?

This is true. You can not browse the local filesystem anymore but there is a sperate feature that allows you to select a local apk (or folder with apk and obb) to side load.

> * adbkit still needs the actual adb executable from what i can tell ?

True. I have also noticed that after I wrote the initial comment.
Still both rclone and adb path can be selected in my version so they don't need to be in the PATH list.

> * i suggest we split these changes up into functional changes, and (frontend)framework changes. as this will make it easier for me ?

I'll see what the best way to do this is. The problem is that almost every fill will be moved or replaced so I'm not Sure what the best way to split those would be.

I think the easiest way would be to ensure that my version matches all the (useful) feature an do a full rebase to the new codebase.

But I'll have a think about this a bit more.
