### ISSUE TITLE
Constant Fetch Errors now showing

### ISSUE THREAD

**Issue by VIPKaiser** [whitewhidow/quest-sidenoder#32]
When upgrading to the 0.0.6-alpha I now get the following errors spamming the console.

Fetch-Error: FetchError: request to http://127.0.0.1:5572/core/stats failed, reason: connect ECONNREFUSED 127.0.0.1:5572
    at ClientRequest.<anonymous> (C:\quest-sidenoder\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}

It makes reading any relevant output impossible.

Windows 10
Running via npm start

I have tried a reinstall and looked for a solution online but can find none.

**Comment by whitewhidow** [comment]
It is attempting to fetch info about the mount's network activity. this should not happen?
Is it mounting successfully ?
Do you see anything usefull beeing logged when trying to mount?
Is rclone indeed running on that port ?

Could you post the entire output up to the point of where it starts showing this error?   

(ps you should be able to just ignore this, and sideload successfully anyway)

thx in advance

**Comment by VIPKaiser** [comment]
> It is attempting to fetch info about the mount's network activity. this should not happen?
Not sure, why it just started happening after i did the update.

> Is it mounting successfully ?
Yes it is mounting correctly and appears to be copying the files to the device absolutely fine!

> Do you see anything usefull beeing logged when trying to mount?
No nothing but this message over and over being spammed in the console.

> Is rclone indeed running on that port ?
> 
> Could you post the entire output up to the point of where it starts showing this error?
Sure. It's below. 
> (ps you should be able to just ignore this, and sideload successfully anyway)
Yes I can still utilise it and it appears to still work. However it's spamming this message constantly. I can't see any other ouput because of it.

> thx in advance

> sidenoder@0.0.6-alpha start C:\quest-sidenoder
> electron-forge start

#START 

√ Checking your system
√ Locating Application
√ Preparing native dependencies
√ Launching Application

(node:44940) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:44940) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
checkMount()
get_device received
check_deps received
checkDeps()
trackDevices()
Current version: 0.0.6-alpha
Github version: v0.0.6-alpha
Using latest version
Fetch-Error: FetchError: request to http://127.0.0.1:5572/core/stats failed, reason: connect ECONNREFUSED 127.0.0.1:5572
    at ClientRequest.<anonymous> (C:\quest-sidenoder\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}

#END 

Thanks

**Comment by VIPKaiser** [comment]
I've uninstalled everything completely. Rebooted. Reinstalled, pulled the latest version and now it's no longer occurring!
