### ISSUE TITLE
"RCLONE global installation not found" when opening sidenoder dmg on Mac

### ISSUE THREAD

**Issue by lucpeng777** [whitewhidow/quest-sidenoder#33]
**Describe the bug**
As directed in the directions, I ran the following code in Terminal:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew cask install android-platform-tools
curl https://rclone.org/install.sh | sudo bash
brew cask install osxfuse

My password was required a few times, and I entered it in, and the last line of the output after stopping was:

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.1
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Installing Cask osxfuse
==> Running installer for osxfuse; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
Password:
installer: Package name is FUSE for macOS
installer: Installing at base path /
installer: The install was successful.
==> Changing ownership of paths required by osxfuse; your password may be necess
🍺  osxfuse was successfully installed!

Any potential causes of this problem, and any suggested fixes?

**Comment by whitewhidow** [comment]
please paste the output of only the following command:
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
(alternatively try to dl and install from the rclone website)

thx

**Comment by lucpeng777** [comment]
Is this what you mean? 
Thanks for helping me.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
==> The following existing directories will have their owner set to lucaspang:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
==> The following existing directories will have their group set to admin:
/usr/local/bin
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/lib/pkgconfig
/usr/local/share/info
/usr/local/share/man
/usr/local/share/man/man1
/usr/local/share/man/man3
/usr/local/share/man/man5
==> The following new directories will be created:
/usr/local/etc
/usr/local/sbin
/usr/local/var
/usr/local/opt
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var/homebrew
/usr/local/var/homebrew/linked
/usr/local/Cellar
/usr/local/Caskroom
/usr/local/Homebrew
/usr/local/Frameworks

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/chmod u+rwx /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5
==> /usr/bin/sudo /usr/sbin/chown lucaspang /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/bin /usr/local/include /usr/local/lib /usr/local/share /usr/local/lib/pkgconfig /usr/local/share/info /usr/local/share/man /usr/local/share/man/man1 /usr/local/share/man/man3 /usr/local/share/man/man5
==> /usr/bin/sudo /bin/mkdir -p /usr/local/etc /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/etc /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /usr/sbin/chown lucaspang /usr/local/etc /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/etc /usr/local/sbin /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /Users/lucaspang/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/lucaspang/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown lucaspang /Users/lucaspang/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 164602 (delta 0), reused 43 (delta 0), pack-reused 164559
Receiving objects: 100% (164602/164602), 42.27 MiB | 9.14 MiB/s, done.
Resolving deltas: 100% (121964/121964), done.
From https://github.com/Homebrew/brew
 * [new branch]      dependabot/bundler/Library/Homebrew/rubocop-1.5.1 -> origin/dependabot/bundler/Library/Homebrew/rubocop-1.5.1
 * [new branch]      master          -> origin/master
 * [new branch]      zsh-fpath-fixes -> origin/zsh-fpath-fixes
 * [new tag]             0.1             -> 0.1
 * [new tag]             0.2             -> 0.2
 * [new tag]             0.3             -> 0.3
 * [new tag]             0.4             -> 0.4
 * [new tag]             0.5             -> 0.5
 * [new tag]             0.6             -> 0.6
 * [new tag]             0.7             -> 0.7
 * [new tag]             0.7.1           -> 0.7.1
 * [new tag]             0.8             -> 0.8
 * [new tag]             0.8.1           -> 0.8.1
 * [new tag]             0.9             -> 0.9
 * [new tag]             0.9.1           -> 0.9.1
 * [new tag]             0.9.2           -> 0.9.2
 * [new tag]             0.9.3           -> 0.9.3
 * [new tag]             0.9.4           -> 0.9.4
 * [new tag]             0.9.5           -> 0.9.5
 * [new tag]             0.9.8           -> 0.9.8
 * [new tag]             0.9.9           -> 0.9.9
 * [new tag]             1.0.0           -> 1.0.0
 * [new tag]             1.0.1           -> 1.0.1
 * [new tag]             1.0.2           -> 1.0.2
 * [new tag]             1.0.3           -> 1.0.3
 * [new tag]             1.0.4           -> 1.0.4
 * [new tag]             1.0.5           -> 1.0.5
 * [new tag]             1.0.6           -> 1.0.6
 * [new tag]             1.0.7           -> 1.0.7
 * [new tag]             1.0.8           -> 1.0.8
 * [new tag]             1.0.9           -> 1.0.9
 * [new tag]             1.1.0           -> 1.1.0
 * [new tag]             1.1.1           -> 1.1.1
 * [new tag]             1.1.10          -> 1.1.10
 * [new tag]             1.1.11          -> 1.1.11
 * [new tag]             1.1.12          -> 1.1.12
 * [new tag]             1.1.13          -> 1.1.13
 * [new tag]             1.1.2           -> 1.1.2
 * [new tag]             1.1.3           -> 1.1.3
 * [new tag]             1.1.4           -> 1.1.4
 * [new tag]             1.1.5           -> 1.1.5
 * [new tag]             1.1.6           -> 1.1.6
 * [new tag]             1.1.7           -> 1.1.7
 * [new tag]             1.1.8           -> 1.1.8
 * [new tag]             1.1.9           -> 1.1.9
 * [new tag]             1.2.0           -> 1.2.0
 * [new tag]             1.2.1           -> 1.2.1
 * [new tag]             1.2.2           -> 1.2.2
 * [new tag]             1.2.3           -> 1.2.3
 * [new tag]             1.2.4           -> 1.2.4
 * [new tag]             1.2.5           -> 1.2.5
 * [new tag]             1.2.6           -> 1.2.6
 * [new tag]             1.3.0           -> 1.3.0
 * [new tag]             1.3.1           -> 1.3.1
 * [new tag]             1.3.2           -> 1.3.2
 * [new tag]             1.3.3           -> 1.3.3
 * [new tag]             1.3.4           -> 1.3.4
 * [new tag]             1.3.5           -> 1.3.5
 * [new tag]             1.3.6           -> 1.3.6
 * [new tag]             1.3.7           -> 1.3.7
 * [new tag]             1.3.8           -> 1.3.8
 * [new tag]             1.3.9           -> 1.3.9
 * [new tag]             1.4.0           -> 1.4.0
 * [new tag]             1.4.1           -> 1.4.1
 * [new tag]             1.4.2           -> 1.4.2
 * [new tag]             1.4.3           -> 1.4.3
 * [new tag]             1.5.0           -> 1.5.0
 * [new tag]             1.5.1           -> 1.5.1
 * [new tag]             1.5.10          -> 1.5.10
 * [new tag]             1.5.11          -> 1.5.11
 * [new tag]             1.5.12          -> 1.5.12
 * [new tag]             1.5.13          -> 1.5.13
 * [new tag]             1.5.14          -> 1.5.14
 * [new tag]             1.5.2           -> 1.5.2
 * [new tag]             1.5.3           -> 1.5.3
 * [new tag]             1.5.4           -> 1.5.4
 * [new tag]             1.5.5           -> 1.5.5
 * [new tag]             1.5.6           -> 1.5.6
 * [new tag]             1.5.7           -> 1.5.7
 * [new tag]             1.5.8           -> 1.5.8
 * [new tag]             1.5.9           -> 1.5.9
 * [new tag]             1.6.0           -> 1.6.0
 * [new tag]             1.6.1           -> 1.6.1
 * [new tag]             1.6.10          -> 1.6.10
 * [new tag]             1.6.11          -> 1.6.11
 * [new tag]             1.6.12          -> 1.6.12
 * [new tag]             1.6.13          -> 1.6.13
 * [new tag]             1.6.14          -> 1.6.14
 * [new tag]             1.6.15          -> 1.6.15
 * [new tag]             1.6.16          -> 1.6.16
 * [new tag]             1.6.17          -> 1.6.17
 * [new tag]             1.6.2           -> 1.6.2
 * [new tag]             1.6.3           -> 1.6.3
 * [new tag]             1.6.4           -> 1.6.4
 * [new tag]             1.6.5           -> 1.6.5
 * [new tag]             1.6.6           -> 1.6.6
 * [new tag]             1.6.7           -> 1.6.7
 * [new tag]             1.6.8           -> 1.6.8
 * [new tag]             1.6.9           -> 1.6.9
 * [new tag]             1.7.0           -> 1.7.0
 * [new tag]             1.7.1           -> 1.7.1
 * [new tag]             1.7.2           -> 1.7.2
 * [new tag]             1.7.3           -> 1.7.3
 * [new tag]             1.7.4           -> 1.7.4
 * [new tag]             1.7.5           -> 1.7.5
 * [new tag]             1.7.6           -> 1.7.6
 * [new tag]             1.7.7           -> 1.7.7
 * [new tag]             1.8.0           -> 1.8.0
 * [new tag]             1.8.1           -> 1.8.1
 * [new tag]             1.8.2           -> 1.8.2
 * [new tag]             1.8.3           -> 1.8.3
 * [new tag]             1.8.4           -> 1.8.4
 * [new tag]             1.8.5           -> 1.8.5
 * [new tag]             1.8.6           -> 1.8.6
 * [new tag]             1.9.0           -> 1.9.0
 * [new tag]             1.9.1           -> 1.9.1
 * [new tag]             1.9.2           -> 1.9.2
 * [new tag]             1.9.3           -> 1.9.3
 * [new tag]             2.0.0           -> 2.0.0
 * [new tag]             2.0.1           -> 2.0.1
 * [new tag]             2.0.2           -> 2.0.2
 * [new tag]             2.0.3           -> 2.0.3
 * [new tag]             2.0.4           -> 2.0.4
 * [new tag]             2.0.5           -> 2.0.5
 * [new tag]             2.0.6           -> 2.0.6
 * [new tag]             2.1.0           -> 2.1.0
 * [new tag]             2.1.1           -> 2.1.1
 * [new tag]             2.1.10          -> 2.1.10
 * [new tag]             2.1.11          -> 2.1.11
 * [new tag]             2.1.12          -> 2.1.12
 * [new tag]             2.1.13          -> 2.1.13
 * [new tag]             2.1.14          -> 2.1.14
 * [new tag]             2.1.15          -> 2.1.15
 * [new tag]             2.1.16          -> 2.1.16
 * [new tag]             2.1.2           -> 2.1.2
 * [new tag]             2.1.3           -> 2.1.3
 * [new tag]             2.1.4           -> 2.1.4
 * [new tag]             2.1.5           -> 2.1.5
 * [new tag]             2.1.6           -> 2.1.6
 * [new tag]             2.1.7           -> 2.1.7
 * [new tag]             2.1.8           -> 2.1.8
 * [new tag]             2.1.9           -> 2.1.9
 * [new tag]             2.2.0           -> 2.2.0
 * [new tag]             2.2.1           -> 2.2.1
 * [new tag]             2.2.10          -> 2.2.10
 * [new tag]             2.2.11          -> 2.2.11
 * [new tag]             2.2.12          -> 2.2.12
 * [new tag]             2.2.13          -> 2.2.13
 * [new tag]             2.2.14          -> 2.2.14
 * [new tag]             2.2.15          -> 2.2.15
 * [new tag]             2.2.16          -> 2.2.16
 * [new tag]             2.2.17          -> 2.2.17
 * [new tag]             2.2.2           -> 2.2.2
 * [new tag]             2.2.3           -> 2.2.3
 * [new tag]             2.2.4           -> 2.2.4
 * [new tag]             2.2.5           -> 2.2.5
 * [new tag]             2.2.6           -> 2.2.6
 * [new tag]             2.2.7           -> 2.2.7
 * [new tag]             2.2.8           -> 2.2.8
 * [new tag]             2.2.9           -> 2.2.9
 * [new tag]             2.3.0           -> 2.3.0
 * [new tag]             2.4.0           -> 2.4.0
 * [new tag]             2.4.1           -> 2.4.1
 * [new tag]             2.4.10          -> 2.4.10
 * [new tag]             2.4.11          -> 2.4.11
 * [new tag]             2.4.12          -> 2.4.12
 * [new tag]             2.4.13          -> 2.4.13
 * [new tag]             2.4.14          -> 2.4.14
 * [new tag]             2.4.15          -> 2.4.15
 * [new tag]             2.4.16          -> 2.4.16
 * [new tag]             2.4.2           -> 2.4.2
 * [new tag]             2.4.3           -> 2.4.3
 * [new tag]             2.4.4           -> 2.4.4
 * [new tag]             2.4.5           -> 2.4.5
 * [new tag]             2.4.6           -> 2.4.6
 * [new tag]             2.4.7           -> 2.4.7
 * [new tag]             2.4.8           -> 2.4.8
 * [new tag]             2.4.9           -> 2.4.9
 * [new tag]             2.5.0           -> 2.5.0
 * [new tag]             2.5.1           -> 2.5.1
 * [new tag]             2.5.10          -> 2.5.10
 * [new tag]             2.5.11          -> 2.5.11
 * [new tag]             2.5.12          -> 2.5.12
 * [new tag]             2.5.2           -> 2.5.2
 * [new tag]             2.5.3           -> 2.5.3
 * [new tag]             2.5.4           -> 2.5.4
 * [new tag]             2.5.5           -> 2.5.5
 * [new tag]             2.5.6           -> 2.5.6
 * [new tag]             2.5.7           -> 2.5.7
 * [new tag]             2.5.8           -> 2.5.8
 * [new tag]             2.5.9           -> 2.5.9
 * [new tag]             2.6.0           -> 2.6.0
 * [new tag]             2.6.1           -> 2.6.1
Updating files: 100% (2451/2451), done.
HEAD is now at a6800dc85 Merge pull request #9514 from Homebrew/sync-triage-config
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
######################################################################### 100.0%
==> Pouring portable-ruby-2.6.3_2.yosemite.bottle.tar.gz
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 855006 (delta 20), reused 26 (delta 12), pack-reused 854966
Receiving objects: 100% (855006/855006), 340.34 MiB | 6.93 MiB/s, done.
Resolving deltas: 100% (576401/576401), done.
Updating files: 100% (5650/5650), done.
Tapped 2 commands and 5374 formulae (5,675 files, 373.4MB).
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics
No analytics data has been sent yet (or will be during this `install` run).

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations

**Comment by whitewhidow** [comment]
my bad i actually ment this one 

`curl https://rclone.org/install.sh | sudo bash`   (the rclone install)

**Comment by lucpeng777** [comment]
zsh: done                   curl https://rclone.org/install.sh | 
zsh: suspended (tty input)  sudo bash
Updating Homebrew...
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
==> Caveats
osxfuse requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

You must reboot for the installation of osxfuse to take effect.

==> Downloading https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.1
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Installing Cask osxfuse
==> Running installer for osxfuse; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
Password:
installer: Package name is FUSE for macOS
installer: Installing at base path /
installer: The install was successful.
==> Changing ownership of paths required by osxfuse; your password may be necess
🍺  osxfuse was successfully installed!

**Comment by whitewhidow** [comment]
install of rclone seems to have gone fine..
Is it now still saying "RCLONE global installation not found" (potentially after a reboot) ?

**Comment by lucpeng777** [comment]
<img width="1440" alt="Screen Shot 2020-12-11 at 4 23 43 PM" src="https://user-images.githubusercontent.com/75865935/101966616-419bdc00-3bcd-11eb-901b-8aef9e55ee6f.png">

Yes. This appeared for a split second(I managed to screenshot) before showing the Rclone global installation not found

**Comment by whitewhidow** [comment]
yep that just briefly shows before the actual check and error,   no clue why it would not find it,  if it actually installed successfully ...

does just running `rclone` in the terminal actually run? (eg. return rclone info) or does it say not found or something ?

also try installing the precompiled binary for rclone via their website (https://rclone.org/downloads/) instead of via brew,   see if that helps ?

**Comment by lucpeng777** [comment]
do you mean just typing in "rclone" in the terminal window? I closed the original terminal window btw. If so, the output is : zsh: command not found: rclone . 

By downloading from rclone, do you mean running this line on terminal: curl https://rclone.org/install.sh | sudo bash
??

**Comment by gpolanco21** [comment]
I'm having the same issue. ''rclone'' is installed and running but still same error.

**Comment by whitewhidow** [comment]
> do you mean just typing in "rclone" in the terminal window? I closed the original terminal window btw. If so, the output is : zsh: command not found: rclone .
> 
> By downloading from rclone, do you mean running this line on terminal: curl https://rclone.org/install.sh | sudo bash
> ??

that response indicates that rclone is infact indeed *not* installed

by downloading from rclone itself i mean running this one : https://downloads.rclone.org/v1.53.3/rclone-v1.53.3-osx-amd64.zip (assuming Intel/AMD - 64 Bit)

**Comment by gpolanco21** [comment]
I closed my terminal and ran "rclone" and it brings up a directory. It's installed. I've restarted my computer but still returns the global error.

**Comment by whitewhidow** [comment]
> I closed my terminal and ran "rclone" and it brings up a directory. It's installed. I've restarted my computer but still returns the global error.

"brings up a directory" ??   please post a screen

**Comment by gpolanco21** [comment]
rclone
Usage:
  rclone [flags]
  rclone [command]

Available Commands:
  about           Get quota information from the remote.
  authorize       Remote authorization.
  backend         Run a backend specific command.
  cat             Concatenates any files and sends them to stdout.
  check           Checks the files in the source and destination match.
  cleanup         Clean up the remote if possible.
  cmount          Mount the remote as file system on a mountpoint.
  config          Enter an interactive configuration session.
  copy            Copy files from source to dest, skipping already copied.
  copyto          Copy files from source to dest, skipping already copied.
  copyurl         Copy url content to dest.
  cryptcheck      Cryptcheck checks the integrity of a crypted remote.
  cryptdecode     Cryptdecode returns unencrypted file names.
  dedupe          Interactively find duplicate filenames and delete/rename them.
  delete          Remove the contents of path.
  deletefile      Remove a single file from remote.
  genautocomplete Output completion script for a given shell.
  gendocs         Output markdown docs for rclone to the directory supplied.
  hashsum         Produces a hashsum file for all the objects in the path.
  help            Show help for rclone commands, flags and backends.
  link            Generate public link to file/folder.
  listremotes     List all the remotes in the config file.
  ls              List the objects in the path with size and path.
  lsd             List all directories/containers/buckets in the path.
  lsf             List directories and objects in remote:path formatted for parsing.
  lsjson          List directories and objects in the path in JSON format.
  lsl             List the objects in path with modification time, size and path.
  md5sum          Produces an md5sum file for all the objects in the path.
  mkdir           Make the path if it doesn't already exist.
  mount           Mount the remote as file system on a mountpoint.
  move            Move files from source to dest.
  moveto          Move file or directory from source to dest.
  ncdu            Explore a remote with a text based user interface.
  obscure         Obscure password for use in the rclone config file.
  purge           Remove the path and all of its contents.
  rc              Run a command against a running rclone.
  rcat            Copies standard input to file on remote.
  rcd             Run rclone listening to remote control commands only.
  rmdir           Remove the path if empty.
  rmdirs          Remove empty directories under the path.
  serve           Serve a remote over a protocol.
  settier         Changes storage class/tier of objects in remote.
  sha1sum         Produces an sha1sum file for all the objects in the path.
  size            Prints the total size and number of objects in remote:path.
  sync            Make source and dest identical, modifying destination only.
  touch           Create new file or change file modification time.
  tree            List the contents of the remote in a tree like fashion.
  version         Show the version number.

Use "rclone [command] --help" for more information about a command.
Use "rclone help flags" for to see the global flags.
Use "rclone help backends" for a list of supported services.

**Comment by lucpeng777** [comment]
yes, same I downloaded from the link you(whitewhindow) gave me, ran the executable in the zip folder downloaded, and the above output shows.

**Comment by whitewhidow** [comment]
> yes, same I downloaded from the link you(whitewhindow) gave me, ran the executable in the zip folder downloaded, and the above output shows.

ah its just the executable ?   i thought it would have been an installer,   yes the executable will ofcourse just give that output

but the rclone command needs to be globally available ("installed" / added to $PATH var) so that it can be ran from anywhere, not just from the folder that the executable is in.   Which is what the command from earlier, the actual install, should have taken care of but for some reason is not.  (verify by running the `rclone` command form the terminal, in a different location than the folder where the executable is actually placed, the command will say not found)

To manually do what the installer should have done for you, add the directory that you downloaded, that contains the rclone directory, to your mac's PATH variable.

How to add a directory to PATH on osx -> https://osxdaily.com/2014/08/14/add-new-path-to-path-command-line/ (include bottom part, "Setting PATH in Shell Profile" to make changes persistant) (might differ slightly on your osx version)
What is PATH variable? ->  https://superuser.com/a/284351 (just for your info)

**Comment by gpolanco21** [comment]
I am not getting anything from following those links. Lucpeng777 I hope you get it. if you could post the code you plug in, that would be awesome.

**Comment by lucpeng777** [comment]
whitewhidow, I'm really confused by the instructions on the website as well. I did as they said and ended up with this mostorous path. i honestly dk how to code in terminal. I also have no idea how to add the changes I made to PATH to my profile to persist.  (BTW the profile name in the screenshot is obviously my fake name, so to the people trying to do stuff, don't bother trying)

<img width="565" alt="Screen Shot 2020-12-11 at 6 47 03 PM" src="https://user-images.githubusercontent.com/75865935/101970769-45395e00-3be1-11eb-9284-07659a8263e2.png">

**Comment by whitewhidow** [comment]
> I also have no idea how to add the changes I made to PATH to my profile to persist.

thats why i went out of my way to give you those 2 links ... (seems you did the first part of it tho, because i see

either properly add the rclone directory to path (or copy the rclone exectuable to an existing PATH directory instead (/usr/local/bin) )

so that rclone becomes available, and sidenoder can use it ....

**Comment by lucpeng777** [comment]
ummmm, i read the two links you sent me and really tried to understand what's written on them, but I'm afraid I still don't have much of a clue on what to type into my terminal besides what I sent to you. Would you mind sending me the line of code you think i should type onto the terminal and I can do so and let you know how that works? Please, thank you.







 \](url)

**Comment by whitewhidow** [comment]
i cant just send copy paste commands because it depends on certain factors.

just copy the rclone executable into the `usr/local/bin` directory, this will also take care of it

(as opposed to adding the new rclone directory to PATH, you just add the rclone executable an the existing PATH directory)

**Comment by gpolanco21** [comment]
Got it working, thank you.

**Comment by Steve-just-steve** [comment]
Had this happen also. Thank you for taking time to explain it not to mention all your work on this. What a treat. **Thanks!**

**Comment by whitewhidow** [comment]
> Had this happen also. Thank you for taking time to explain it not to mention all your work on this. What a treat. **Thanks!**

you're welcome,   thank YOU for taking the time to search trough existing issues before just re-posting the same thing again !

**Comment by saurabh-jadhav-09** [comment]
Exact same error for me but on windows, since windows does not have a bin directory what am i supposed to do?
