### ISSUE TITLE
Browse Mount update or Installed apps update...

### ISSUE THREAD

**Issue by VIPKaiser** [whitewhidow/quest-sidenoder#37]
Please can you either make the installed apps like the browse mount interface and show any updates with a ribbon like the Multiplayer one.

or 

Update the browse mount view to show an INSTALLED ribbon or marker again with any updates available would be amazing!

**Comment by Treehouse40oz** [comment]
When I click browse mount, nothing happens. It does not load or anything. Have used for the last month with no issues. Tried installing again and followed the steps. But no luck. I am connected and green at the top with the headset on.

**Comment by 666dsa666** [comment]
> When I click browse mount, nothing happens. It does not load or anything. Have used for the last month with no issues. Tried installing again and followed the steps. But no luck. I am connected and green at the top with the headset on.

Same issue here :(

**Comment by whitewhidow** [comment]
please consider reading the first 2 lines in the current readme ...
https://github.com/whitewhidow/quest-sidenoder/blob/main/readme.md
