### ISSUE TITLE
Keep mount files on local disk

### ISSUE THREAD

**Issue by cherokee93** [whitewhidow/quest-sidenoder#40]
**Is your feature request related to a problem? Please describe.**
My internet is slow, it takes a lot of time to download all the files I want to install. I've used Resilio Sync to keep files local in past but those are without fancy MP flairs/ auto-updates.

**Describe the solution you'd like**
It would be awesome to have a resilio share of your rclone /mnt folder so I can keep it local on my HD and have easier access.
(It's not the same as the folders on the VRP resilio share are not labeled correctly so I can't use that)

![image](https://user-images.githubusercontent.com/12370126/103149950-040f8500-476f-11eb-897f-9200b1b2d35e.png)
VS
![image](https://user-images.githubusercontent.com/12370126/103149962-12f63780-476f-11eb-8110-b9135f1423c1.png)

**Additional context**
Thanks for your work, Sidenoder it's awesome 👍👍👍

**Comment by whitewhidow** [comment]
Feel free to set one up and be the first seeder, but i have not had anyone show interest in a resilio sync so far..

**Comment by cherokee93** [comment]
Uhm, I've found another way. 
I ended up copying your rclone config in my **.config/rclone/rclone.conf** and set up a crontab to run the following every night:

> 0 5 * * * rclone sync WHITEWHIDOW_QUEST: /mnt/charlie/Downloads/QuestSync -P

So it works very good this way, except for updates. Can you please tell me where is the file to set the mount directory on?

**Comment by whitewhidow** [comment]
please dont do it this way,   as this will eat the drive's bandwidth for no real good reason ...
If you want to clone the entire drive,   i suggest you just get a google drive,    and then you can just sync them entirely serverside, that way it wont affect gdrive's rate limits or use up your bandwidth (it will just send straight from one drive to other)

now it will pull 250+ gig and boom, ratelimits exceeded for everyone...

so pls kindly dont do it this way, else i will start revoking and renewing the key daily :/

**Comment by cherokee93** [comment]
> please dont do it this way, as this will eat the drive's bandwidth for no real good reason ...
> If you want to clone the entire drive, i suggest you just get a google drive, and then you can just sync them entirely serverside, that way it wont affect gdrive's rate limits or use up your bandwidth (it will just send straight from one drive to other)
> 
> now it will pull 250+ gig and boom, ratelimits exceeded for everyone...
> 
> so pls kindly dont do it this way, else i will start revoking and renewing the key daily :/

Oh sorry, didn't meant to eat all your bandwidth. I don't fully understand how do quotas work in gdrive to be honest 🤔 
Now that I have the full folder it will only sync deletions and new versions, but i will stop it.

That's why something like a resilio sync it's needed (but I understand it's hard to implement/not wanted by any sidenoder user), so it works for everybody and it doesn't have any limit, I can't have updated versions to seed (without being you) nor a good upload speed to seed.

Sorry again, I'll cancel my crontab and edit my comment above

**Comment by whitewhidow** [comment]
just posting this link here for reference so that github links them (both issues basically asking for a way of keeping local files after dl)

https://github.com/whitewhidow/quest-sidenoder/issues/41

**Comment by whitewhidow** [comment]
closing in favour of https://github.com/whitewhidow/quest-sidenoder/issues/41
