### ISSUE TITLE
Add Drag & Drop support for apk & OBB 

### ISSUE THREAD

**Issue by VIPKaiser** [whitewhidow/quest-sidenoder#43]
I have a huge selection of local files on my hard drive. Being able to drag and drop these to install them would be AMAZING!

The other app does this, but there is zero feedback and your app is becoming way better imo.

**Comment by whitewhidow** [comment]
Could you try running this build :

https://github.com/whitewhidow/quest-sidenoder/actions/runs/449710346

and **dropping** an **apk** onto it  (**onto the 'body' part of the page**, _not on the blank space on the bottom, under the bottom text_)   and seeing if it works ?   (cant test with hmd this instant)

**Comment by VIPKaiser** [comment]
yeah, no problem!

**Comment by whitewhidow** [comment]
can you try again using this one :
https://github.com/whitewhidow/quest-sidenoder/actions/runs/451644380
(should fix the resulting error you accidentally posted in the other issue

**Comment by whitewhidow** [comment]
should be fixed in 
https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.12

please confirm

**Comment by whitewhidow** [comment]
closing as it seems to work (atleast on linux and mac for sure), feel free to reopen if it turns out it does not on windows
