### ISSUE TITLE
Show Device space | Available | Used

### ISSUE THREAD

**Issue by VIPKaiser** [whitewhidow/quest-sidenoder#45]
When the headset is connected it would be great to see the total space of the device, the available space, and the space used.

**Comment by whitewhidow** [comment]
that is already visible on the installed apps page ..?

**Comment by VIPKaiser** [comment]
Can it be visible in the title bar or in the header if possible?

**Comment by whitewhidow** [comment]
have added it to the browse page aswell now (these are the only 2 pages where it makes sense to see this info, no home or settings page.

is in dev branch, no release yet, since im doing some refactoring and not sure what i broke ;)
If you dont mind,   pull and run development branch

**Comment by VIPKaiser** [comment]
No problem. I'll do that now. Thank you!
