### ISSUE TITLE
Get app Info

### ISSUE THREAD

**Issue by nero12** [whitewhidow/quest-sidenoder#46]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
it would be awsome to be able to get more information about the individual games straight from your app.

**Comment by whitewhidow** [comment]
what app info ?

I'll add a link to the relevant steam/oculus/sidequest pages ?

**Comment by fadelchaidarf** [comment]
App info as in the games size would be great to determine whether a game is worth downloading or not
