### ISSUE TITLE
can't launch sidenoder, ADB global installation not found

### ISSUE THREAD

**Issue by redlai360** [whitewhidow/quest-sidenoder#50]
**Describe the bug**
I have installed Sidenoder according to the instructions:
1) Download and unpack the latest windows release from https://github.com/whitewhidow/quest-sidenoder/releases/latest
2) Run the windows-install.bat script and follow the onscreen instructions (this will install 7ZIP, GIT, NODE, ADB, RCLONE and WINFSP)
3) restart computerç
4) Run the sidenoder.exe application

However, when I start the application apears the Error Message: ADB global installation not found, please read the README on github.

ADB is working fine as I open SideQuest and it is connected to my Oculus.

I have tried the version 0.013 and it give me the same error.

Thank you for your support.

**Desktop:**
 - OS: Windows
 - Running via sidenoder.exe
 - Version  v0.0.14

**Comment by whitewhidow** [comment]
Check that the actually install passes without errors.

As clearly adb is not actually installed globally on your machine.
Sideaquest uses it's own included adb exectuable, it does not install it,
so having sidequest work does not mean you I stalled adb, the error means
you did not install adb, hence the install failed.

Please read the actual output when running commands.

**Comment by redlai360** [comment]
reinstalled and now it is working. Thank you
