### ISSUE TITLE
Rclone not installed

### ISSUE THREAD

**Issue by A1450** [whitewhidow/quest-sidenoder#53]
Followed al the steps but it still says I don't have rclone.

**Comment by whitewhidow** [comment]
If it says you dont have rclone **installed**, then you dont have rclone **installed**..
Find a way to **install** rclone
(**installed**, and **downloaded**, are two different things)

**Comment by A1450** [comment]
The install bat was supposed to install it though right?

**Comment by whitewhidow** [comment]
> The install bat was supposed to install it though right?
Assuming you are on windows yes (that is what the questions are for, that are asked when creating a ticket)
Also, since you dont mention any errors or unusual output, i assume that if you ran the windows install script, it ran without errors or incidents?
