### ISSUE TITLE
Error: ENOSPC: no space left on device

### ISSUE THREAD

**Issue by matthew-stafford** [whitewhidow/quest-sidenoder#54]
**Describe the bug**

**To Reproduce**
Install walking dead or beat saber

**Expected behavior**
Installing obb sometimes causes the error : Error: ENOSPC: no space left on device
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - AppImage
 - Version 0.0.15

**Additional context**

Device isnt out of space, it has 100gb free space.

(node:8439) UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, copyfile '/tmp/mnt/Beat Saber v147+1.13.0 -QU (with DLC, BMBF) -versionCode-147 -packageName-com.beatgames.beatsaber -steam-620980/com.beatgames.beatsaber/fakelove' -> '/tmp/com.beatgames.beatsaber/fakelove'
(node:8439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8439) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by whitewhidow** [comment]
Your local disk on your pc has no space left.
(Sidenoder copys the file from the drive to your hmd first, before moving
it to the device)

**Comment by matthew-stafford** [comment]
My local disk has 450GB free space, I think the limit is in the /tmp partition. Looks like I can manually resize /tmp to temporarily fix the issue with the following command.

`mount -o remount,size=16G,noatime /tmp`

I would assume most people using a Linux based OS would have this issue? If so, can you include an option to download files to a specified directory? or remove files straight after copying so that it doesnt fill the entire partition.

Thanks for the software, it is awesome :)

**Comment by Punchwes** [comment]
Can I ask if I am able to delete these local copies? I have very limited OS storage and want to remove them after installing to my headset. If possible can I ask where can I locate the cache folder....

**Comment by whitewhidow** [comment]
> Can I ask if I am able to delete these local copies? I have very limited OS storage and want to remove them after installing to my headset. If possible can I ask where can I locate the cache folder....

they are be placed in your systems temp folder (in a suberforlder with the same name as the packagename of the title)
They will be auto deleted upon reboot (since they are in your systems temp dir)
