### ISSUE TITLE
Please add option to change download location

### ISSUE THREAD

**Issue by illtellyoulater** [whitewhidow/quest-sidenoder#63]
Please add option to choose a different drive as a target for downloaded files. 
As you know lots of people use small SSD drives as primary drives for OS, so it would be better if we could choose to download files to a different location.

**Comment by ChaosNicro** [comment]
Just tried a symlink for /tmp/mnt to an hdd-folder with moderate success on Linux.
It still tries to copy the obb-files to /tmp before pushing them to the device and I can't really symlink the entire mountpoint.
Maybe a path in the settings.json that replaces all calls to /tmp would be ideal.
