### ISSUE TITLE
Rclone global installation not found

### ISSUE THREAD

**Issue by hashchecked** [whitewhidow/quest-sidenoder#64]
I had previously installed sidenoder and it worked perfectly. when the new update was released I as previously done on other updates, deleted the files and reinstalled the update this time after running the windows install it throws errors. this is what it shows. please help. I just recently started getting the ERROR access denied codes. 

7-zip is present
Downloading rclone
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.2M  100 13.2M    0     0  6773k      0  0:00:02  0:00:02 --:--:-- 6061k
Downloading adb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0     98      0  0:00:01 --:--:--  0:00:01   348
100 11.5M  100 11.5M    0     0  11.5M      0  0:00:01 --:--:--  0:00:01 11.5M
Unzipping rclone
Unzipping adb
ERROR: Can not delete output file : Access is denied. : .\platform-tools\AdbWinApi.dll
ERROR: Can not delete output file : Access is denied. : .\platform-tools\AdbWinUsbApi.dll
ERROR: Can not delete output file : Access is denied. : .\platform-tools\adb.exe
Combining folders
The system cannot find the file specified.
The system cannot find the file specified.
Adding to PATH

WARNING: The data being saved is truncated to 1024 characters.

SUCCESS: Specified value was saved.
.
WinFsp is present
.
.
Dependencies installed.
You can run "SideNoder.exe"
Press any key to continue . . .

**Comment by hashchecked** [comment]
7-zip is present
Downloading rclone
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.2M  100 13.2M    0     0  6773k      0  0:00:02  0:00:02 --:--:-- 5011k
Downloading adb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0     98      0  0:00:01 --:--:--  0:00:01   392
100 11.5M  100 11.5M    0     0  11.5M      0  0:00:01 --:--:--  0:00:01 11.5M
Unzipping rclone
Unzipping adb
Combining folders
The system cannot find the file specified.
The system cannot find the file specified.
Adding to PATH

WARNING: The data being saved is truncated to 1024 characters.

SUCCESS: Specified value was saved.
.
WinFsp is present
.
.
Dependencies installed.
You can run "SideNoder.exe"
Press any key to continue . . .

this is typical

**Comment by whitewhidow** [comment]
ERROR: Can not delete output file : Access is denied. : .\platform-tools\AdbWinApi.dll
ERROR: Can not delete output file : Access is denied. : .\platform-tools\AdbWinUsbApi.dll
ERROR: Can not delete output file : Access is denied. : .\platform-tools\adb.exe

you can not delete files that are in use, eg, you cannot delete adb while it is running ....
