### ISSUE TITLE
SideNoder constantly saying drive mount status disconnected even though all my drives are mounted and whenever i click it it keeps staying red after refreshing. I am running MacOS.

### ISSUE THREAD

**Issue by soapbooger** [whitewhidow/quest-sidenoder#67]

**Comment by soapbooger** [comment]
@whitewhidow please help ive been trying to fix so many things since the past 4 hours this is the last one i was encountering i think

**Comment by soapbooger** [comment]
and yes i reinstalled the app, rebooted, restarted

**Comment by whitewhidow** [comment]
sounds like an osxfuse issue
you can try manually configuring and mounting an rclone drive, and seeing what the error is.
Other than that, cant help, this is not an issue with sidenoder, but with your mac
