### ISSUE TITLE
Can't launch SideNoder - RCLONE global installation not found, please read the README on github

### ISSUE THREAD

**Issue by CerealMs** [whitewhidow/quest-sidenoder#70]
Good morning,
On the launch of SideNoder, a red error appears saying "RCLONE global installation not found, please read the README on github"

I did the installation multiple times, also did the manual installation, tried in admin too, but the error keep appearing.

I am on Windows 10 Pro 20H2, and have Avast free as an antivirus (disabled during installation and running).

It is a first installation of SideNode, I never used it before (used Rookie)

Thank you.

![image](https://user-images.githubusercontent.com/81803035/113400411-0f8fcf00-93a2-11eb-8f12-415de65c2eb2.png)

**Comment by whitewhidow** [comment]
please paste the ouput of the install script

**Comment by CerealMs** [comment]
7-zip is present
Downloading rclone
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.5M  100 13.5M    0     0  13.5M      0  0:00:01 --:--:--  0:00:01 14.2M
Downloading adb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0     98      0  0:00:01 --:--:--  0:00:01   628
100 11.6M  100 11.6M    0     0  11.6M      0  0:00:01 --:--:--  0:00:01 11.6M
Unzipping rclone
Unzipping adb
Combining folders
The system cannot find the file specified.
The system cannot find the file specified.
Adding to PATH

SUCCESS: Specified value was saved.
.
WinFsp is present
.
.
Dependencies installed.
You can run "SideNoder.exe"

**Comment by CerealMs** [comment]
Also, the ADB and rclone files are present in sideloader_deps

**Comment by whitewhidow** [comment]
rclone has changed versions again.
updating new release, will be up in 20 mins or so.
will update ticket once up

**Comment by whitewhidow** [comment]
Please try the following release:
https://github.com/whitewhidow/quest-sidenoder/releases/tag/v0.0.18

the install should now run without these 2 lines:

> The system cannot find the file specified.
The system cannot find the file specified.

**Comment by CerealMs** [comment]
I, sadly, have still the same exact error :
![image](https://user-images.githubusercontent.com/81803035/113404229-1cafbc80-93a8-11eb-94c7-21ddbea0f9eb.png)

Also, the .exe that is in the windows zip is still noted as 0.0.17 ?
![image](https://user-images.githubusercontent.com/81803035/113404499-892abb80-93a8-11eb-8cd3-3b79866b17fc.png)

I also now have a notification when launching the program saying a new version is available, even tho I'm launching the new version downloaded.
![image](https://user-images.githubusercontent.com/81803035/113404456-7c0dcc80-93a8-11eb-865e-842d23e4ed66.png)

**Comment by whitewhidow** [comment]
fml github builds are acting up again, sec

**Comment by whitewhidow** [comment]
https://github.com/whitewhidow/quest-sidenoder/releases/download/v0.0.18/sidenoder-win-x64-exe.zip

please try again (download has been replaced)

**Comment by CerealMs** [comment]
Everything works perfectly !
Thank you so much for your hard work !
