### ISSUE TITLE
mounting

### ISSUE THREAD

**Issue by itachiuchiha1234** [whitewhidow/quest-sidenoder#71]
hello I am a Mac user and I have installed all the necicary things needed for sidenoder and for some reason it is not mounting I have deleted and reinstalled macfuse/osxfuse countless time aswell as the app sidenoder itself and for some reason nothing works

**Comment by whitewhidow** [comment]
The only thing else you can try is to manually configure a drive in rclone using `rclone config`
https://rclone.org/commands/rclone_config/

Then try to manually mount the drive using `rclone mount`
https://rclone.org/commands/rclone_mount/

And see if it produces any usefull error, other than that, there is not much i can do

**Comment by itachiuchiha1234** [comment]
by drive do you mean google drive

**Comment by whitewhidow** [comment]
any 'drive provider' supported by rclone will do, since the problem is most likely in the actual mount procedure, no matter which 'drive provider' it is

**Comment by itachiuchiha1234** [comment]
could you point me towards a video of a tutorial for that please

**Comment by whitewhidow** [comment]
no,      i dont have any links to any video tutorials of rclone, just links to the documentation
