### ISSUE TITLE
Cleaning apps (ex: ccleaner) may delete all your files/games if it's mounted 😅

### ISSUE THREAD

**Issue by jlvcm** [whitewhidow/quest-sidenoder#72]
**Describe the bug**
Cleaning apps (ex: ccleaner) will delete randomly all your games if it's mounted as it is mounted to a/tmp folder (AppData/Local/Temp)

**To Reproduce**
1. connect the device
2. Mount the device
3. run ccleaner

**Expected behavior**
Not loose everything

**Desktop (please complete the following information):**
 - OS: Windows
 - Running via binary
 - Version 0.0.18

**Comment by whitewhidow** [comment]
Your machine does not have write permissions to the drive anyway, so nothing will actually be removed.
You dont actually 'loose everything' at all..

**Comment by jlvcm** [comment]
i know this is probably a wontfix, anyway, but i saw some apks getting deleted from the TMP folder, and most apps stop working after that until i installed them again,

but maybe was something else I did wrong, thanks for the quick answer!
