### ISSUE TITLE
Quest won't connect

### ISSUE THREAD

**Issue by eternalbluepetya** [whitewhidow/quest-sidenoder#74]
I'm on Ubuntu, and I've enabled developer mode and USB debugging on my quest. My mount status is connected, but for some reason my quest status stays at disconnected.

**Comment by whitewhidow** [comment]
you probably did not accept the prompt inside of the hmd.

please post the complete output of the 'adb devices' command

**Comment by eternalbluepetya** [comment]
When I do adb devices it says 
'List of devices attached
1WMHH835B11072	unauthorized'

**Comment by eternalbluepetya** [comment]
Nevermind, for some reason it started working after I did adb devices again enough times. (I know, weird.)

**Comment by whitewhidow** [comment]
> When I do adb devices it says
> 'List of devices attached
> 1WMHH835B11072 unauthorized'

> Nevermind, for some reason it started working after I did adb devices again enough times. (I know, weird.)

the _unauthorized_ means you had not accepted the prompt inside your headset, surely now that it works, it no longer says _unauthorized_.

closing issue now
