### ISSUE TITLE
Certain Games not Sideloading

### ISSUE THREAD

**Issue by eternalbluepetya** [whitewhidow/quest-sidenoder#75]
(Sorry for two issues in one day...) I'm using Linux, and everything is connected and mounted. When I download the game I want though, which is Beat Saber, it does not show up in the unknown sources games. I've tried both my own apk and the one on the sideloader. It doesn't even show up in the installed apps section. A different game sideloaded though, (not a game, just a small test application I found to test it on.) so I'm, not sure what's going on.

**Comment by whitewhidow** [comment]
1. you probably let the hmd fall asleep,or lost connection for some other reason
2. no sideloaded games show in installed apps, they all show under unknown sources

either way, sorry, but not a software issue

**Comment by eternalbluepetya** [comment]
I already said, it wasn't showing under unknown sources. I spent quite a fair time trying to install this with different apks of beat saber, none of them worked. (Some I kept the headset on the entire time.)
