### ISSUE TITLE
cant open sideloader

### ISSUE THREAD

**Issue by AlexNova1555** [whitewhidow/quest-sidenoder#76]
after installing to the new verison 0.0.19
it says to me this message
RCLONE global installation not found, please read the README on github.
and rclone is installed in the sideloader_deps folder
any idea why its happening?

**Comment by whitewhidow** [comment]
can you paste the output of the install script pls

**Comment by AlexNova1555** [comment]
yes here is  the output


7-zip is present
Downloading rclone
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.5M  100 13.5M    0     0  13.5M      0  0:00:01  0:00:01 --:--:-- 8559k
Downloading adb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    98  100    98    0     0     98      0  0:00:01 --:--:--  0:00:01   417
100 11.6M  100 11.6M    0     0  11.6M      0  0:00:01  0:00:01 --:--:-- 14.6M
Unzipping rclone
Unzipping adb
Combining folders
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
Adding to PATH

SUCCESS: Specified value was saved.
.
WinFsp is present
.
.
Dependencies installed.
You can run "SideNoder.exe"
Press any key to continue . . .

**Comment by whitewhidow** [comment]
installer in 0.0.19 seems broken.
creating new release 0.0.20 (you may just aswell just reinstall 0.0.18, there are no significant changes)

**Comment by whitewhidow** [comment]
reverted now in v0.0.20

thx for reporting
