### ISSUE TITLE
x32 Builds

### ISSUE THREAD

**Issue by sawzaw78** [whitewhidow/quest-sidenoder#78]
**Is your feature request related to a problem? Please describe.**
App will not build on my machine (Pi 3)

**Describe the solution you'd like**
x32 builds would easily solve this and don’t take much time to build

**Describe alternatives you've considered**
GitHub Actions could be used to build these. https://github.com/samuelmeuli/action-electron-builder

**Comment by whitewhidow** [comment]
> App will not build on my machine (Pi 3)

maybe post the output, so that i can see what the actual problem is ...
