### ISSUE TITLE
Browse Mount not working.

### ISSUE THREAD

**Issue by Treehouse40oz** [whitewhidow/quest-sidenoder#79]
**Describe the bug**
After connecting headset. When I click browse mount, nothing happens. It does not load or anything. Have used for the last month with no issues. Tried installing again and followed the steps to install again. But no luck.I see i am connected with both green boxes. Dev mode on etc..

**To Reproduce**
1. Go to 'Browse'
2. Click on 'Click to Browse Mounts'

**Expected behavior**
When you click browse mounts, nothing will happen. Almost as if you did not click it. 

**Screenshots**

**Desktop (Windows 10 64bit Version10.0.19042):**
 - OS: [e.g. Windows/OSX/LINUX]
 - Running via binary or npm start
 - Version [e.g. v0.0.3-alpa]

**Additional context**

**Comment by whitewhidow** [comment]
all you can really do it reinstall rclone, reoot, and hope it works again, sounds like rclone stopped doing its job for you for some reason

**Comment by Treehouse40oz** [comment]
Thank you, I restarted and reinstalled and was working properly! Thanks
