### ISSUE TITLE
Mac - storage bar not showing, mount and quest status connected

### ISSUE THREAD

**Issue by AcesChuck** [whitewhidow/quest-sidenoder#80]
**Describe the bug**
I do not believe I have a strong connection to the Q2, although it says mount and quest status connected. Stuck at "Trying to fetch device storage" as the storage bar is not showing.

When trying to sideload a game, it goes through the whole process and appears to work but cannot see game in Q2.

In the console, seeing this error: "GET https://vrdb.app/oculus/images/2301375123298882.jpg 404 (Not Found)"

**Screenshots**
<img width="1680" alt="Screen Shot 2021-05-14 at 11 33 33 PM" src="https://user-images.githubusercontent.com/84220001/118351049-83c7a180-b50e-11eb-8641-e6fbe3a82452.png">

**Desktop (please complete the following information):**
 - OS: OSX Big Sur
 - Version 0.0.21

**Comment by whitewhidow** [comment]
means adb oes nto have proper access
(re)accept the prompt inside the headset

if still having issues after accepting, post the response of the `adb devices` command here

**Comment by AcesChuck** [comment]
sorry, new to this, just got the q2 yesterday, I did accept the "allow access to data" prompt within the headset but nothing changed, is it because i have another app installed on my mac, Android File Transfer?

where can i find the "response of the adb devices command"? did you mean inputting "abd devices" into the terminal? if so, the response was "-bash: abd: command not found".

**Comment by whitewhidow** [comment]
answered on telegram
