### ISSUE TITLE
Can't mount drive in temp folder

### ISSUE THREAD

**Issue by carlxo** [whitewhidow/quest-sidenoder#81]
I cannot get Rclone to mount the drive in quest-sidenoder v0.0.21 installed with npm on Windows. This however works for me when I run it on macOS.

1. Execute 'npm start'
2. Click on 'Mount status'
3. Console in Quest-Sidenoder-Linux throws error:
'check_mount responded: {"success":false, "mountFolder": "C:/Users/USER/AppData/Local/Temp/mnt"}'
4. npm in cmd throws:
'error: Command failed: rclone mount --read-only --rc --rc-no-auth --config=C:\Users\USER\AppData\Local\Temp\c WHITEWHIDOW_QUEST: C:/Users/USER/AppData/Local/Temp/mnt
2021/05/19 14:54:39 Failed to start remote control: start server failed: listen tcp 127.0.0.1:5572: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.'

Expected behavior:
Drive should mount in temp folder.

Desktop:
 - OS: Windows 10 Pro 20H2
 - Running via npm start
 - Version v0.0.21

**Comment by whitewhidow** [comment]
error seems pretty clear ? 

2021/05/19 14:54:39 Failed to start remote control: start server failed: listen tcp 127.0.0.1:5572: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.'

something is already running on that port

**Comment by carlxo** [comment]
I ran netstat -ab and checked the entire list and I can't find anything running on TCP 127.0.0.1:5572

![netstat -ab](https://user-images.githubusercontent.com/34350926/118969215-17fd9280-b96d-11eb-9fba-d04e5c0aacf3.png)

Can I change the port used somewhere to check?

**Comment by whitewhidow** [comment]
im not following,     sidenoder doesnt auto-run rclone (unless you changed it in settings),    so i dont see why rclone would start when just starting sidenoder?

**Comment by carlxo** [comment]
I did set it to automatically mount on start-up, yes. Scratching my head at what's going on. Everything is added to path, port isn't used. I can successfully mount the drive/mirrors through other apps like Rclone Browser or Rookie's just fine, but I like your app the best, so here I am trying everything I can think of.

**Comment by whitewhidow** [comment]
well first off disable the auto mount,    as otherwise it is pointless to send the error, as it will just say port in use,   since it is already running .    try running the `rclone mount --read-only --rc --rc-no-auth --config=C:\Users\USER\AppData\Local\Temp\c WHITEWHIDOW_QUEST: C:/Users/USER/AppData/Local/Temp/mnt` command manually, while having sidenoder open, BUT not having rclone running previously, and inspect the response

**Comment by carlxo** [comment]
First off, thanks for trying to help!
It really is appreciated. As I said before it works on my Mac and I really like the software. Anyway:

If I launch rclone manually with sidenoder running there is no issue, I get:
```
2021/05/22 01:51:21 NOTICE: Serving remote control on http://localhost:5572/
The service rclone has been started.
```
I press Ctrl+C and I stop the service.

If I now press _Mount Status_ in Sidenoder I get:
```
error: Command failed: rclone mount --read-only --rc --rc-no-auth --config=C:\Users\carlxo\AppData\Local\Temp\c WHITEWHIDOW_QUEST: C:/Users/carlxo/AppData/Local/Temp/mnt
2021/05/22 01:48:43 NOTICE: Serving remote control on http://localhost:5572/
The service rclone has been started.

GEVONDE
checkMount()
exec_error
exec_stderr

checkMount()
```

Rclone process is now running, if I try to press _Mount Status_ again I get this, like before:
```
checkMount()
exec_stderr

error: Command failed: rclone mount --read-only --rc --rc-no-auth --config=C:\Users\carlxo\AppData\Local\Temp\c WHITEWHIDOW_QUEST: C:/Users/carlxo/AppData/Local/Temp/mnt
2021/05/22 01:54:13 Failed to start remote control: start server failed: listen tcp 127.0.0.1:5572: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.

GEVONDE
checkMount()
```

I can close out the process and get the first result again. Neither results in a successful mount.

I didn't mean to file this as a bug, it's probably some issue with my system, but thanks for helping anyway. I'll update if I find something so maybe it can help someone else.

**Comment by whitewhidow** [comment]
when you ran it manually , outside of sidenoder, make sure you are running it with the actual parameters `rclone mount --read-only --rc --rc-no-auth --config=C:\Users\carlxo\AppData\Local\Temp\c WHITEWHIDOW_QUEST: C:/Users/carlxo/AppData/Local/Temp/mnt`      not JUST rclone

second   im really confused by what you are saying next, you click mount the first time,  and it does mount without error ?   but doesnt show as mounted in sidenoder ?   and then when you click it a second time,   it error about the port ?   correct?

am i correct in understanding that the forst mount DOES actually work, but is jsut not reflected as mounted, in sidenoder ?   can you conform that ?    is the mount folder actually created at `C:/Users/carlxo/AppData/Local/Temp/mnt` after running the first successfull mount command ?

**Comment by carlxo** [comment]
I have managed to find the conflict!

I was able to connect to the drive when I disconnected from _ExpressVPN_. Specifically the process _mDNSResponder.exe_ seems to share that same port on my system. So Sidenoder is now working as expected, I'll close the issue. Thanks for the support!
