### ISSUE TITLE
No drive mounted

### ISSUE THREAD

**Issue by BattleCat77** [whitewhidow/quest-sidenoder#85]
I am an absolute beginner in both sidenoder and GitHub so apologies in advance.

I have installed sidenoder successfully on my Mac but when I ope it up there are not games showing and it says "Drive not mounted, browsing local content only"

Top right there is a red rectangle with Mount Status: Disconnected

Am I missing something or doing something wrong at all?

**Comment by whitewhidow** [comment]
Top right there is a red rectangle with Mount Status: Disconnected -> click this, does it turn green ?

**Comment by BattleCat77** [comment]
Thanks for responding, 

I do and it just stays disconnected 

to I need to add anything to my sidenoder to direct it somewhere?

**Comment by BattleCat77** [comment]
Uploading 64462449963__21F691EA-7EBA-46F9-85F8-A1E5FA9B5AEF.MOV…

**Comment by whitewhidow** [comment]
if mounting is not working, and you're on mac, its 99% sure that your osxfuse install is not working properly

**Comment by BattleCat77** [comment]
Oh no really? I’m using big Sur
