### ISSUE TITLE
unable to install rclone

### ISSUE THREAD

**Issue by sereyphut** [whitewhidow/quest-sidenoder#88]
I have install homebrew, ADB, OSXFUSE (as well as for big sur). But when I tried to run "curl https://rclone.org/install.sh | sudo bash" in terminal, it seems to appeared that "curl: (7) Failed to connect to rclone.org port 443: Operation timed out". what does it indicate and is there any solution to it ?

**Comment by whitewhidow** [comment]
1. it means, what it literally says in the error . that rclone.org is down
2. read the readme and notice that i no longer maintain this repo.
