### ISSUE TITLE
quest-sidenoder does not work in windows 11

### ISSUE THREAD

**Issue by Shark1337** [whitewhidow/quest-sidenoder#91]
it does not connect with the oculus, permissions have already been given

**Screenshots**
![image](https://user-images.githubusercontent.com/6165744/124462398-f37d3e80-dd91-11eb-8cdb-988f7e7f3afd.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/
 - Version  0.31

**Comment by whitewhidow** [comment]
TRY READING THE FIRST LINE OF THE README IN THIS REPO .    WHY ON EARTH ARE YOU POSTING HERE ?
