### ISSUE TITLE
Browse mount not working

### ISSUE THREAD

**Issue by Punchwes** [whitewhidow/quest-sidenoder#92]
**Describe the bug**
The setup seems to be fine, but when I click browse mount, nothing happens:

**To Reproduce**

**Expected behavior**
A list of games shown up

**Screenshots**
uploaded

![1901626368064_ pic](https://user-images.githubusercontent.com/19360686/125827482-90fbb6cd-c84d-4a98-8a9c-a75f0162af9a.jpg)

![1911626368278_ pic_hd](https://user-images.githubusercontent.com/19360686/125827521-ae3e0d16-8d5c-4ebc-9e9c-53885f62bb3f.jpg)

**Desktop (please complete the following information):**
 - OS: OSx
  Platform Detected: darwin
   Temp Dir Detected: /var/folders/gv/z_6yynkd2sjchc5710zh5sjm0000gn/T
   Mount Dir Detected: /var/folders/gv/z_6yynkd2sjchc5710zh5sjm0000gn/T/mnt
   ADB Installed.
   RCLONE Installed.

**Additional context**

**Comment by whitewhidow** [comment]
try reading the first 2 lines in the readme
