### ISSUE TITLE
click to browse mount broken

### ISSUE THREAD

**Issue by michitslol** [whitewhidow/quest-sidenoder#93]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows/OSX/LINUX]
 - Running via binary or npm start
 - Version [e.g. v0.0.3-alpa]

**Additional context**

**Comment by siddhartpai** [comment]
Hi @whitewhidow this is still broken.
