### ISSUE TITLE
Can't download any APK since today, facing E10

### ISSUE THREAD

**Issue by Purpleistacky** [whitewhidow/quest-sidenoder#95]
Here's the error

Error: EIO: i/o error, copyfile '/var/folders/4k/53m0fyjn7lj6vl29sbtcb2dm0000gn/T/mnt/Quest Games/Demeo v107128443+1.7.128443 -FFA/com.resolutiongames.demeo.apk' -> '/var/folders/4k/53m0fyjn7lj6vl29sbtcb2dm0000gn/T/com.resolutiongames.demeo.apk.part'

**Comment by whitewhidow** [comment]
Wrong repo read readme
