### ISSUE TITLE
mounting

### ISSUE THREAD

**Issue by rhyolitedv** [whitewhidow/quest-sidenoder#96]
hey can i ask how to mount the drive?? and the drive link itself??

**Comment by rhyolitedv** [comment]
mount status stays disconnected even after i refresh it a couple of times

**Comment by whitewhidow** [comment]
wrong repo read readme

**Comment by rhyolitedv** [comment]
hey can i ask what do u mean by wrong repo?

**Comment by whitewhidow** [comment]
WRONG REPO, **READ FIRST LINE OF README** .
