### ISSUE TITLE
ADB not found

### ISSUE THREAD

**Issue by RiotNorality** [whitewhidow/quest-sidenoder#98]
**When i follow the directions for windows and launch Sidenoder.exe it says ADB not found**

Also i dont know how to do the npm start command

![image](https://user-images.githubusercontent.com/92702988/149666216-01ba8a91-7f0d-4a19-bba3-e8464593de17.png)

**Comment by RiotNorality** [comment]
I also asked the same question on the discord if u can help me there

**Comment by whitewhidow** [comment]
read readme, wrong repo.
